name: Reusable workflow for adding issues to the web project board

on:
  issues:
    types:
      - opened
      - labeled
  workflow_call:

jobs:
  add_issues_to_project_board:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1.7.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Add issues to project board
        uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/paritytech/projects/44
          github-token: ${{ steps.generate_token.outputs.token }}